### ISSUE TITLE
Readme instructions for data population

### ISSUE THREAD

**Issue by charlesvardeman** [zazuko/ontology-manager#6]
It is a bit unclear from the readme where the development/example ontology database fixtures for the maritime domain are populated from and how to customize for deployment (for development and production) within other domains. It would be helpful to have a short section similar to the theme customization instructions that explain how to customize the starting vocabulary structure for a different domain of interest.   My assumption (although I haven't had time to verify this yet) that customization of snapshots.js facilitates the population of the initial database instances?

As an aside, my impression from briefly exploring the tool locally is that this is a very useful contribution to the ontology development community and would like to thank Zazuko for open-sourcing this tool for a broader community.

**Comment by vhf** [comment]
Thanks for the feedback, that's a good opportunity for us to improve the documentation. Before I do, let's try to answer all your questions.

> where the development/example ontology database fixtures for the maritime domain are populated from and how to customize for deployment (for development and production) within other domains.

The ontology is not stored in a database, it is stored on GitHub (supporting other forges such as GitLab would be pretty easy but we haven't had the need yet).

http://editor.zazuko.com/ for instance pulls its content from: https://github.com/zazuko/zom-ontology-demo , and pushes ontology modifications to it (attributing the commit to its author since users sign in using their GitHub account via OAuth).

The editor needs two files: one for the "structure" and one for the actual content of the ontology. We noticed it is often easier to work on an ontology by grouping concepts into an overarching, artificial structure that should not be part of the ontology. Think of the structure as something used to group classes and concepts and display them in their respective groups in the ontology manager interface.

We should definitely provide some guidance as to how these two files are supposed to be structured to bootstrap a new ontology.

snapshot.js is only used by the test suite. :)

---

If you follow the 4 steps here: https://github.com/zazuko/ontology-manager#1-get-oauth-credentials , you should be able to sign in locally at http://localhost:3000 . After signing in, navigate to the admin panel > editor settings: http://localhost:3000/admin/settings . From there you will be able to change the configuration of your editor. In the configuration form, 2.2 is where the ontology location is configured:

<img width="808" alt="Screen Shot 2020-01-15 at 18 19 18" src="https://user-images.githubusercontent.com/2022803/72455772-b307ba80-37c3-11ea-8301-27ad3581fd12.png">

**Comment by charlesvardeman** [comment]
Thanks, this makes complete sense that it pulls the triples from GitHub. I will look at the sample ontology and structure triples as a basis for my experiments.

**Comment by vhf** [comment]
@charlesvardeman Here's some more documentation about this. It's still work in progress and I'll rework the README (split it into different parts in a `docs/` folder probably) when I'm done with it but it might still help you even though it's a partial draft: <https://hackmd.io/gnJvuXHgRSC-YuZrDU5lhw?view>

**Comment by vhf** [comment]
Here's some more documentation: https://zazuko.github.io/ontology-manager/ontology-files.html , I'm closing this issue for now, please get back to us should you have more questions!
